name: Test Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies (if any)
        run: pip install -r requirements.txt || echo "No requirements file found, skipping installation."

      - name: List directory contents
        run: ls -la

      - name: Test secrets
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: python test_secrets.py

      # Test end-to-end by uploading two artifacts and then downloading them 
      - name: Create artifact files
        run: |
          mkdir -p test/dir1
          echo "Lorem ipsum dolor sit amet" > test/dir1/file1.txt

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: test/dir1/file1.txt

