name: Test Secrets

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Test secrets
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Testing secret:"
          python -c "import os; print(os.getenv('MY_SECRET'))"
